services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "80:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.19"
      ENABLE_COMMAND_BLOCK: "TRUE"
      WORLD: "${MINECAFT_WORLD_PATH}"
    volumes:
      - /data:/data